# Generated by Django 4.0 on 2021-12-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_option_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='question_fk',
        ),
    ]
