# Generated by Django 4.0 on 2021-12-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_question_option_question_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question_fk',
            new_name='select_question',
        ),
    ]
